"""SYNTHETIC data generator — smoke tests only.

Everything this module writes is fake.  It exists so the *whole* pipeline
(ingest -> audit -> train -> evaluate -> figures) can be exercised end to end
without the real 2 GB GDSC download.

Project rule R2: synthetic runs must be unmistakable.  The generator drops a
``SYNTHETIC`` marker file in the data root; :func:`is_synthetic` is consulted by
the training and reporting code, which then stamps ``SYNTHETIC`` into run names,
logs and report headings.  Never present a number produced from this data as a
result.
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

import numpy as np
import pandas as pd

from hill.utils.logging import get_logger

log = get_logger("data.synthetic")

MARKER = "SYNTHETIC"


def is_synthetic(data_root: str | Path) -> bool:
    return (Path(data_root) / MARKER).exists()


def _hill(log_c: np.ndarray, e_inf: float, slope: float, midpoint: float) -> np.ndarray:
    return e_inf + (1.0 - e_inf) / (1.0 + np.exp(slope * (log_c - midpoint)))


def generate(
    data_root: str | Path = "data",
    n_cells: int = 40,
    n_drugs: int = 12,
    n_genes: int = 400,
    n_doses: int = 7,
    n_pathways: int = 60,
    n_patients: int = 30,
    n_patches: int = 24,
    histo_dim: int = 64,
    seed: int = 0,
) -> dict[str, str]:
    """Write a miniature but structurally faithful copy of every input file."""
    rng = np.random.default_rng(seed)
    root = Path(data_root)
    raw = root / "raw"
    (root).mkdir(parents=True, exist_ok=True)
    (root / MARKER).write_text(
        "This data directory contains SYNTHETIC data generated by "
        "hill.data.synthetic. No result derived from it is a scientific result.\n",
        encoding="utf-8",
    )

    cosmic = [str(900000 + i) for i in range(n_cells)]
    genes = [f"GENE{i:04d}" for i in range(n_genes)]
    drug_ids = list(range(1, n_drugs + 1))

    # --- latent biology: cells and drugs have low-rank factors ---------------
    k = 4
    cell_f = rng.normal(size=(n_cells, k))
    drug_f = rng.normal(size=(n_drugs, k))
    gene_loadings = rng.normal(size=(k, n_genes))
    expr = 6.0 + cell_f @ gene_loadings * 0.6 + rng.normal(0, 0.3, size=(n_cells, n_genes))

    # true curve parameters: efficacy driven by one factor, potency by another
    e_raw = -1.2 + 0.9 * (cell_f[:, [0]] @ drug_f[:, [0]].T) + rng.normal(0, 0.4, (n_cells, n_drugs))
    e_inf = 1.0 / (1.0 + np.exp(-e_raw))
    slope = np.exp(0.1 * (cell_f[:, [1]] @ drug_f[:, [1]].T) + rng.normal(0, 0.2, (n_cells, n_drugs)))
    midpoint = 0.5 * (cell_f[:, [2]] @ drug_f[:, [2]].T) + rng.normal(0, 0.5, (n_cells, n_drugs))

    max_conc = np.array([10.0 ** rng.integers(0, 3) for _ in range(n_drugs)], dtype=float)

    # --- raw plate wells ----------------------------------------------------
    rows = []
    plate_size = 6
    for ci, cid in enumerate(cosmic):
        barcode = f"PLATE{ci // plate_size:03d}"
        scan = f"SCAN{ci // plate_size:03d}"
        neg, pos = 1000.0, 100.0
        for _ in range(8):
            rows.append((barcode, scan, np.nan, np.nan, np.nan, "NC-1", neg + rng.normal(0, 15)))
        for _ in range(4):
            rows.append((barcode, scan, np.nan, np.nan, np.nan, "B", pos + rng.normal(0, 5)))
        for di, did in enumerate(drug_ids):
            for d in range(1, n_doses + 1):
                conc = max_conc[di] / (2.0 ** (d - 1))
                v = _hill(np.log(conc), e_inf[ci, di], slope[ci, di], midpoint[ci, di])
                intensity = pos + (neg - pos) * float(v) + rng.normal(0, 12)
                rows.append((barcode, scan, cid, did, conc, f"L{did}-D{d}-S", intensity))
    raw_wells = pd.DataFrame(
        rows, columns=["BARCODE", "SCAN_ID", "COSMIC_ID", "DRUG_ID", "CONC", "TAG", "INTENSITY"]
    )
    (raw / "gdsc_raw").mkdir(parents=True, exist_ok=True)
    raw_path = raw / "gdsc_raw" / "GDSC2_public_raw_data_SYNTHETIC.csv"
    raw_wells.to_csv(raw_path, index=False)

    # --- published two-parameter fit ---------------------------------------
    # The "published" LN_IC50 is what a *bottom-fixed* (GDSC official) fit
    # returns for these curves, so the synthetic file reproduces the real
    # phenomenon: when the true bottom is high, the fitted midpoint is pushed
    # past the maximum tested concentration and the label becomes censored.
    from hill.audit.curvefit import fit_curves

    doses = np.stack([np.log(max_conc[di] / 2.0 ** np.arange(n_doses)) for di in range(n_drugs)])
    x_grid = np.repeat(doses[None, :, :], n_cells, axis=0).reshape(n_cells * n_drugs, n_doses)
    y_true = _hill(
        x_grid,
        np.repeat(e_inf.reshape(-1, 1), n_doses, axis=1),
        np.repeat(slope.reshape(-1, 1), n_doses, axis=1),
        np.repeat(midpoint.reshape(-1, 1), n_doses, axis=1),
    )
    m2 = fit_curves(
        x_grid.astype(np.float32), y_true.astype(np.float32),
        np.ones_like(x_grid, dtype=bool), model="M2", steps=400, n_restarts=2,
    )
    published_ln_ic50 = m2.params["xmid"].reshape(n_cells, n_drugs)

    fitted_rows = []
    for ci, cid in enumerate(cosmic):
        for di, did in enumerate(drug_ids):
            e = e_inf[ci, di]
            ln_ic50 = float(published_ln_ic50[ci, di])
            fitted_rows.append(
                {
                    "COSMIC_ID": cid,
                    "DRUG_ID": did,
                    "DRUG_NAME": f"SynthDrug{did}",
                    "CELL_LINE_NAME": f"SYNTH-{ci}",
                    "LN_IC50": ln_ic50 + rng.normal(0, 0.15),
                    "AUC": float(np.clip(e + (1 - e) * 0.5, 0, 1)),
                    "RMSE": abs(rng.normal(0.08, 0.02)),
                    "MAX_CONC": max_conc[di],
                    "DATASET": "GDSC2",
                }
            )
    (raw / "gdsc_fitted").mkdir(parents=True, exist_ok=True)
    pd.DataFrame(fitted_rows).to_csv(
        raw / "gdsc_fitted" / "GDSC2_fitted_dose_response_SYNTHETIC.csv", index=False
    )

    # --- omics --------------------------------------------------------------
    (raw / "omics").mkdir(parents=True, exist_ok=True)
    expr_df = pd.DataFrame(np.expm1(expr).T, index=genes, columns=[f"DATA.{c}" for c in cosmic])
    expr_df.insert(0, "GENE_title", ["synthetic gene"] * n_genes)
    expr_df.insert(0, "GENE_SYMBOLS", genes)
    expr_df.to_csv(raw / "omics" / "Cell_line_RMA_proc_basalExp_SYNTHETIC.txt", sep="\t", index=False)

    mut_rows = []
    for ci, cid in enumerate(cosmic):
        hit = rng.choice(genes, size=max(3, n_genes // 40), replace=False)
        mut_rows.extend({"model_id": cid, "gene_symbol": g} for g in hit)
    pd.DataFrame(mut_rows).to_csv(raw / "omics" / "mutations_all_SYNTHETIC.csv", index=False)

    cnv = pd.DataFrame(
        rng.integers(-2, 3, size=(n_genes, n_cells)).astype(float),
        index=genes, columns=[f"DATA.{c}" for c in cosmic],
    )
    cnv.insert(0, "gene_symbol", genes)
    cnv.to_csv(raw / "omics" / "cnv_gistic_SYNTHETIC.csv", index=False)

    # --- pathways -----------------------------------------------------------
    (raw / "pathways").mkdir(parents=True, exist_ok=True)
    with (raw / "pathways" / "ReactomePathways_SYNTHETIC.gmt").open("w", encoding="utf-8") as fh:
        for p in range(n_pathways):
            members = rng.choice(genes, size=int(rng.integers(12, 40)), replace=False)
            fh.write("\t".join([f"SYNTH_PATHWAY_{p}", "synthetic"] + list(members)) + "\n")

    # --- compound annotation ------------------------------------------------
    (raw / "gdsc_annotation").mkdir(parents=True, exist_ok=True)
    pd.DataFrame(
        {
            "DRUG_ID": drug_ids,
            "DRUG_NAME": [f"SynthDrug{d}" for d in drug_ids],
            "SYNONYMS": ["" for _ in drug_ids],
            "TARGET": ["SYNTH_TARGET" for _ in drug_ids],
            "TARGET_PATHWAY": [f"SynthPathway{d % 4}" for d in drug_ids],
        }
    ).to_csv(raw / "gdsc_annotation" / "screened_compounds.csv", index=False)

    # --- TCGA-like target domain -------------------------------------------
    tcga = raw / "tcga"
    tcga.mkdir(parents=True, exist_ok=True)
    patients = [f"SYN-PAT-{i:03d}" for i in range(n_patients)]
    pat_f = rng.normal(size=(n_patients, k))
    pat_expr = np.expm1(6.0 + pat_f @ gene_loadings * 0.6 + rng.normal(0, 0.3, (n_patients, n_genes)))
    pd.DataFrame(pat_expr, index=patients, columns=genes).to_parquet(tcga / "expression_tpm.parquet")
    pd.DataFrame(
        rng.integers(0, 2, size=(n_patients, n_genes)).astype(float), index=patients, columns=genes
    ).to_parquet(tcga / "mutations_binary.parquet")

    treat_rows = []
    for pi, pid in enumerate(patients):
        for did in rng.choice(drug_ids, size=2, replace=False):
            kill = 1.0 - float(1.0 / (1.0 + np.exp(-(pat_f[pi, 0] * 1.2 - 0.2))))
            responder = rng.random() < kill
            treat_rows.append(
                {
                    "patient_id": pid,
                    "treatment_type": "Pharmaceutical Therapy, NOS",
                    "therapeutic_agents": f"SynthDrug{did}",
                    "treatment_outcome": "Partial Response" if responder else "Progressive Disease",
                    "treatment_intent": "Adjuvant",
                    "days_to_treatment_start": int(rng.integers(0, 200)),
                }
            )
    pd.DataFrame(treat_rows).to_csv(tcga / "treatments.csv", index=False)
    pd.DataFrame({"patient_id": patients, "vital_status": "Alive"}).to_csv(tcga / "clinical.csv", index=False)

    # --- pre-extracted "UNI" features --------------------------------------
    histo_dir = root / "processed" / "uni_features"
    histo_dir.mkdir(parents=True, exist_ok=True)
    for pi, pid in enumerate(patients[: max(1, n_patients // 2)]):
        feats = rng.normal(size=(n_patches, histo_dim)).astype(np.float32) + pat_f[pi, 0]
        np.save(histo_dir / f"{pid}.npy", feats)

    # --- synthetic Cmax table (fake values, clearly marked) -----------------
    cmax_path = root / "clinical_cmax_SYNTHETIC.csv"
    pd.DataFrame(
        {
            "drug_id": drug_ids,
            "drug_name": [f"SynthDrug{d}" for d in drug_ids],
            "cmax_um": [float(max_conc[i] / 2.0) for i in range(n_drugs)],
            "source": ["SYNTHETIC"] * n_drugs,
            "verified": [False] * n_drugs,
            "notes": ["synthetic"] * n_drugs,
        }
    ).to_csv(cmax_path, index=False)

    truth = pd.DataFrame(
        {
            "cell_id": np.repeat(cosmic, n_drugs),
            "drug_id": np.tile(drug_ids, n_cells),
            "true_e_inf": e_inf.reshape(-1),
            "true_slope": slope.reshape(-1),
            "true_midpoint": midpoint.reshape(-1),
        }
    )
    truth.to_parquet(root / "processed" / "synthetic_truth.parquet", index=False)

    summary = {
        "marker": str(root / MARKER),
        "raw_wells": str(raw_path),
        "n_cells": n_cells,
        "n_drugs": n_drugs,
        "n_genes": n_genes,
        "n_patients": n_patients,
        "histology_dir": str(histo_dir),
        "cmax_csv": str(cmax_path),
    }
    log.warning("generated SYNTHETIC data under %s — results from it are not scientific results", root)
    (root / "processed").mkdir(parents=True, exist_ok=True)
    (root / "processed" / "synthetic_manifest.json").write_text(json.dumps(summary, indent=2), encoding="utf-8")
    return summary


def main(argv: list[str] | None = None) -> int:
    ap = argparse.ArgumentParser(description="Generate SYNTHETIC data for smoke tests")
    ap.add_argument("--data-root", default="data_smoke")
    ap.add_argument("--seed", type=int, default=0)
    ap.add_argument("--n-cells", type=int, default=40)
    ap.add_argument("--n-drugs", type=int, default=12)
    args = ap.parse_args(argv)
    summary = generate(args.data_root, n_cells=args.n_cells, n_drugs=args.n_drugs, seed=args.seed)
    print(json.dumps(summary, indent=2))
    return 0


if __name__ == "__main__":
    sys.exit(main())
