"""Run every Gate-0 audit and write ``reports/gate0.md``.

    python -m hill.audit.run_gate0 --config configs/base.yaml

Exit codes
    0  all gates passed
    2  G-1 failed  -> the ingest pipeline does not reproduce published fits.
                      STOP: do not train anything (project rule R1).
    3  G-3 failed  -> M3 does not beat M2. The premise of the design is not
                      supported by the data. STOP and report.
"""

from __future__ import annotations

import argparse
import sys
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

from hill.audit import availability, censoring, raw_access, refit, variance
from hill.audit.base import audit_dir, is_synthetic
from hill.config import load_config
from hill.utils.logging import get_logger
from hill.utils.provenance import capture_provenance, git_hash

log = get_logger("audit.gate0")


def _fmt(x: Any, digits: int = 4) -> str:
    if isinstance(x, float):
        return "n/a" if x != x else f"{x:.{digits}f}"
    return str(x)


def write_report(cfg: Any, results: dict[str, Any], path: Path) -> None:
    g1, g2, g3, g4, g5 = (results.get(k, {}) for k in ("G1", "G2", "G3", "G4", "G5"))
    synth = is_synthetic(cfg)
    banner = (
        "> **SYNTHETIC DATA — NOT A SCIENTIFIC RESULT.** Every number below was computed on "
        "simulated data generated by `hill.data.synthetic`.\n\n"
        if synth
        else ""
    )
    cfg_path = getattr(cfg, "_source_path", "configs/base.yaml")

    lines: list[str] = [
        "# Gate 0 — data validity audit",
        "",
        banner,
        f"- generated: {datetime.now(timezone.utc).isoformat(timespec='seconds')}",
        f"- git: `{git_hash()}`",
        f"- config: `{cfg_path}`",
        f"- data root: `{cfg.paths.data_root}`",
        "",
        "## Summary",
        "",
        "| gate | question | verdict |",
        "|---|---|---|",
        f"| G-1 | Can we read and correctly normalise raw viability? | **{'PASS' if g1.get('passed') else 'FAIL'}** |",
        f"| G-2 | How much of the published label set is censored? | {_fmt(100 * g2.get('censored_fraction_overall', float('nan')), 1)}% |",
        f"| G-3 | Does a free-bottom model beat the official fit? | **{'SUPPORTED' if g3.get('premise_supported') else 'NOT SUPPORTED'}** |",
        f"| G-4 | Share of label variance from the drug main effect | f_drug = {_fmt(g4.get('f_drug'), 3)} |",
        f"| G-5 | TCGA patients with omics + slides + outcome | {g5.get('n_patients_omics_slide_outcome', 'n/a')} |",
        "",
        "## G-1 — raw viability accessibility",
        "",
        "Reproduction command: `python -m hill.audit.raw_access --config " + str(cfg_path) + "`",
        "",
        f"- pairs audited: {g1.get('n_pairs_audited')} of {g1.get('n_pairs_total')}",
        f"- measurements: {g1.get('n_points')}",
        f"- points per pair: mean {_fmt(g1.get('points_per_pair', {}).get('mean'), 2)}, "
        f"median {_fmt(g1.get('points_per_pair', {}).get('median'), 1)}, "
        f"range [{_fmt(g1.get('points_per_pair', {}).get('min'), 0)}, "
        f"{_fmt(g1.get('points_per_pair', {}).get('max'), 0)}]",
        f"- our M2 refit vs published LN_IC50: Pearson r = **{_fmt(g1.get('ic50_pearson_vs_published'), 3)}**, "
        f"Spearman = {_fmt(g1.get('ic50_spearman_vs_published'), 3)}, "
        f"median |Δ| = {_fmt(g1.get('ic50_median_abs_diff'), 3)}",
        f"- our AUC vs published AUC: r = {_fmt(g1.get('auc_pearson_vs_published'), 3)}",
        f"- pairs with no published fit: {g1.get('missing_pattern', {}).get('pairs_without_published_fit')}",
        f"- batched-vs-scipy optimiser check: median relative RSS excess = "
        f"{_fmt(g1.get('scipy_crosscheck', {}).get('median_relative_rss_excess'), 5)}",
        "",
        "## G-2 — censoring",
        "",
        "Reproduction command: `python -m hill.audit.censoring --config " + str(cfg_path) + "`",
        "",
        f"- censored (LN_IC50 > ln MAX_CONC): **{_fmt(100 * g2.get('censored_fraction_overall', float('nan')), 1)}%** "
        f"({g2.get('n_censored')} / {g2.get('n_pairs')} pairs)",
        f"- drugs censored for every cell line: {g2.get('drugs_fully_censored')} of {g2.get('n_drugs')}",
        f"- drugs never censored: {g2.get('drugs_never_censored')}",
        "- per-drug table: `results/gate0/g2_censoring_per_drug.csv`",
        "",
        "## G-3 — two-parameter vs three-parameter refit (decisive)",
        "",
        "Reproduction command: `python -m hill.audit.refit --config " + str(cfg_path) + "`",
        "",
        f"- per-pair RMSE: M2 {_fmt(g3.get('rmse_M2', {}).get('median'))} vs M3 {_fmt(g3.get('rmse_M3', {}).get('median'))} (median)",
        f"- M3 fits better on {_fmt(100 * g3.get('fraction_M3_better_rmse', float('nan')), 1)}% of pairs "
        f"(Wilcoxon p = {_fmt(g3.get('wilcoxon_p_M3_better'), 3)})",
        f"- M3 preferred by AIC on {_fmt(100 * g3.get('fraction_M3_preferred_AIC', float('nan')), 1)}%, "
        f"by BIC on **{_fmt(100 * g3.get('fraction_M3_preferred_BIC', float('nan')), 1)}%** of pairs",
        f"- fitted E_inf: median {_fmt(g3.get('e_inf_distribution', {}).get('median'), 3)}, "
        f"IQR [{_fmt(g3.get('e_inf_distribution', {}).get('q25'), 3)}, "
        f"{_fmt(g3.get('e_inf_distribution', {}).get('q75'), 3)}]",
        f"- E_inf >= 0.5 (no IC50 exists): {_fmt(100 * g3.get('fraction_e_inf_ge_0.5', float('nan')), 1)}%; "
        f"E_inf <= 0.05 (M2 adequate): {_fmt(100 * g3.get('fraction_e_inf_le_0.05', float('nan')), 1)}%",
        f"- overlap of high-E_inf and censored pairs: Jaccard {_fmt(g3.get('censoring_overlap', {}).get('jaccard'), 3)}, "
        f"P(high E_inf | censored) = {_fmt(g3.get('censoring_overlap', {}).get('p_high_einf_given_censored'), 3)} "
        f"vs P(high E_inf | uncensored) = {_fmt(g3.get('censoring_overlap', {}).get('p_high_einf_given_uncensored'), 3)}",
        f"- mean per-drug correlation between refitted ln IC50 and Emax: "
        f"{_fmt(g3.get('mean_per_drug_pcc_ic50_vs_emax'), 3)} "
        "(low values mean a scalar label discards a lot)",
        "- per-pair refit: `results/gate0/g3_refit_per_pair.parquet`",
        "",
        "## G-4 — drug main-effect share",
        "",
        "Reproduction command: `python -m hill.audit.variance --config " + str(cfg_path) + "`",
        "",
        f"- f_drug = {_fmt(g4.get('f_drug'), 3)}; drug-pooled correlations are "
        f"{'dominated by the drug main effect and are not reported' if g4.get('global_pcc_would_be_misleading') else 'still drug-influenced; per-drug metrics are reported regardless'}",
        "",
        "## G-5 — TCGA availability",
        "",
        "Reproduction command: `python -m hill.audit.availability --config " + str(cfg_path) + "`",
        "",
        f"- patients with all omics: {g5.get('n_patients_all_omics')}",
        f"- patients with slide features: {g5.get('n_patients_with_slide_features')}",
        f"- patients with omics AND slides: {g5.get('n_patients_omics_and_slide')}",
        f"- evaluable treatment outcomes: {g5.get('n_evaluable_outcomes')} "
        f"({g5.get('n_patients_with_evaluable_outcome', 'n/a')} patients)",
        f"- drugs with a clinical Cmax: {g5.get('cmax', {}).get('n_with_value', 'n/a')} "
        f"of {g5.get('cmax', {}).get('n_drugs_listed', 'n/a')} listed; "
        f"verified: {g5.get('cmax', {}).get('n_verified', 'n/a')}",
        f"- drugs excluded from the clinical loss (no Cmax): "
        f"{', '.join(g5.get('cmax', {}).get('drugs_without_cmax', [])) or 'none'}",
        "",
        "## Decision",
        "",
    ]
    if not g1.get("passed"):
        lines += [
            "**STOP — G-1 failed.** Our normalisation does not reproduce the published fits, so the "
            "ingest pipeline cannot be trusted. No model is trained until this is resolved.",
        ]
    elif not g3.get("premise_supported"):
        lines += [
            "**STOP — G-3 did not support the premise.** The free-bottom model does not beat the "
            "official two-parameter fit on this data, so the argument that the label-generating model "
            "is misspecified is not supported here. Report this rather than proceeding to deep learning.",
        ]
    else:
        lines += [
            "Both blocking gates passed: raw viability is accessible and correctly normalised, and the "
            "free-bottom model is preferred over the official two-parameter fit. Proceeding to §4-§7.",
        ]
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")
    log.info("wrote %s", path)


def run_all(cfg: Any, max_pairs: int | None = None, steps: int = 800) -> dict[str, Any]:
    results = {
        "G1": raw_access.run(cfg, max_pairs=max_pairs),
        "G2": censoring.run(cfg),
        "G3": refit.run(cfg, max_pairs=max_pairs, steps=steps),
        "G4": variance.run(cfg),
        "G5": availability.run(cfg),
    }
    report_path = Path(cfg.paths.reports_dir) / "gate0.md"
    write_report(cfg, results, report_path)
    capture_provenance(audit_dir(cfg) / "gate0_provenance.json", cfg, extra={
        "g1_passed": results["G1"].get("passed"),
        "g3_premise_supported": results["G3"].get("premise_supported"),
    })
    return results


def main(argv: list[str] | None = None) -> int:
    ap = argparse.ArgumentParser(description="Run all Gate-0 audits")
    ap.add_argument("--config", default="configs/base.yaml")
    ap.add_argument("--set", nargs="*", default=[])
    ap.add_argument("--max-pairs", type=int, default=None, help="subsample pairs (speed)")
    ap.add_argument("--steps", type=int, default=800, help="optimiser steps per curve fit")
    ap.add_argument("--allow-fail", action="store_true", help="return 0 even if a gate fails")
    args = ap.parse_args(argv)

    cfg = load_config(args.config, overrides=args.set)
    cfg.paths.ensure()
    setattr(cfg, "_source_path", args.config)
    results = run_all(cfg, max_pairs=args.max_pairs, steps=args.steps)

    print(f"\nGate 0 report: {Path(cfg.paths.reports_dir) / 'gate0.md'}")
    if not results["G1"].get("passed"):
        print("G-1 FAILED — stopping (see reports/gate0.md)")
        return 0 if args.allow_fail else 2
    if not results["G3"].get("premise_supported"):
        print("G-3 did not support the premise — stopping (see reports/gate0.md)")
        return 0 if args.allow_fail else 3
    print("Gate 0 passed.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
